### PR TITLE
Create predefined size lists

### PR DESCRIPTION
**Pull request by nshishov**
Since we know size of returned arrays it's better to create lists with defined capacity.

### CODE REVIEW

**Comment by Uriil** [comment]
Could you please introduce named constants, instead of using raw numbers? So instead of 7 we will use DAYS_IN_ONE_WEEK and instead of 2 CONVERSION_RATES_COUNT(or u can name them using Pascal case DaysInOneWeek, ConversionRratesCount, just stay consistent)

**Comment by nshishov** [comment]
Please check.

**Comment by Uriil** [comment]
Merged

**Comment by nshishov** [comment]
Thx

**Pull request merged**
