### PR TITLE
UserRecordNew now returns newly created login

### PR DESCRIPTION
**Pull request by coldwateryu**
or -1 if error

### CODE REVIEW

**Comment by Uriil** [comment]
Thank you for your pull request, but I can not accept it.

Main reason, it's breaking change, which will silently affect all existing applications.
Second one, in this case we are loosing error reason.
And third one, I would like to keep API as close to original one as possible

**Comment by coldwateryu** [comment]
I understand. As a point of interest, how do you retrieve the newly created account number?

**Comment by Uriil** [comment]
It will be assigned to Login property of passed userRecord parameter

**Comment by pantonis** [comment]
I totally agree with @Uriil. It would break the logic. As he stated you just check the Login property of the UserRecord that you pass. It should have the newly created account login.

**Comment by coldwateryu** [comment]
Thanks for the info, you're very helpful, I'll try and do that.

**Pull request closed without merging**
